In [2]:
import numpy as np

In [3]:
import random

Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

Задание 3
Решите систему уравнений: <br>
4x + 2y + z = 4 <br>
x + 3y = 12 <br>
5y + 4z = -3 <br>

# Task 1

In [4]:
n = 12
np.arange(n, -1, -1)

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# Task 2

In [9]:
n = 12
x = np.arange(n, -1, -1)
arr = np.diag(x)
arr.sum()

78

# Task 3

In [10]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

np.linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [11]:
np.allclose( np.dot(a, np.linalg.solve(a, b)), b )

True

# Task 4

In [13]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [14]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0], # man 0
        [1, 1, 2, 1, 0, 0], # man 1
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [15]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [16]:
users_stats.shape

(10, 6)

In [17]:
max_sim = 0
max_user = []
for i in range(users_stats.shape[0]):
    print(users_stats[i])
    cos_sim = cosine(users_stats[i], next_user_stats)
    print("Cosine ", cos_sim)
    degree = np.arccos(cosine(users_stats[i], next_user_stats)) * 360 / 2 / np.pi
    print("Degree ", degree)
    if max_sim < cos_sim:
        max_sim = cos_sim
        max_user = users_stats[i]

[2 1 0 0 0 0]
Cosine  0.19999999999999996
Degree  78.46304096718453
[1 1 2 1 0 0]
Cosine  0.8451542547285165
Degree  32.311533237423866
[2 0 1 0 0 0]
Cosine  0.3999999999999999
Degree  66.42182152179818
[1 1 2 1 0 1]
Cosine  0.7905694150420948
Degree  37.761243907035045
[0 0 1 2 0 0]
Cosine  0.3999999999999999
Degree  66.42182152179818
[0 0 0 0 0 5]
Cosine  0.0
Degree  90.0
[1 0 0 0 0 0]
Cosine  0.0
Degree  90.0
[0 1 1 0 0 0]
Cosine  0.9486832980505138
Degree  18.434948822922017
[0 0 0 1 1 3]
Cosine  0.0
Degree  90.0
[1 0 0 2 1 4]
Cosine  0.0
Degree  90.0


In [18]:
print(max_user, max_sim)

[0 1 1 0 0 0] 0.9486832980505138
